version: '3'
services:
  db:
    container_name: eduwork_db
    image: mysql:8.0.25
    working_dir: /home
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - db.env
    volumes:
      - ./../../data/mysql/db:/var/lib/mysql
      - ./../../data/mysql/init:/home
    ports:
      - 3306:3306
    networks:
      - backend

  app:
    container_name: eduwork_app
    image: peron:php8.1-fpm
    volumes:
      - ./../../../Asmeldi/Laravel_Vue.js/library:/var/www/html
    depends_on:
      - db
    networks:
      - backend

  web:
    container_name: eduwork_web
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./../../../Asmeldi/Laravel_Vue.js/library:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - app

networks:
  backend: