version: '3'
services:
  db:
    container_name: eduwork_db
    image: mysql:8.0.25
    working_dir: /home
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - db.env
    volumes:
      - ./../data/mysql:/var/lib/mysql
      - ./../init:/home
    ports:
      - 3306:3306
    networks:
      - eduwork_network

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - eduwork_network

  php:
    container_name: eduwork_php
    image: php:7.4-fpm-alpine
    volumes:
      - ./../../src:/var/www/html
    networks:
      - eduwork_network

  web:
    container_name: eduwork_web
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./../../src/:/var/www/html
      - ./../config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # - ./../../config/local/nginx/module.conf/fastcgi_cache.conf.example:/etc/nginx/module.conf/fastcgi_cache.conf
      # - ./../../log/local/nginx:/var/log/nginx
      - ./../data/nginx/ngx_fastcgi_cache:/var/nginx/ngx_fastcgi_cache
    networks:
      - eduwork_network
    depends_on:
      - php

networks:
  eduwork_network: